# Generated by Django 4.2.3 on 2023-07-26 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_machine', models.CharField(max_length=32)),
                ('type_machine', models.CharField(choices=[('PD1,5', 'ПД1,5'), ('PG1,5', 'ПГ1,5'), ('PD2,0', 'ПД2,0'), ('PD2,5', 'ПД2,5'), ('PD3,0', 'ПД3,0'), ('PD5,0', 'ПД5,0')], default='PD1,5', max_length=12)),
                ('n_motor', models.CharField(max_length=32)),
                ('type_motor', models.CharField(choices=[('D1803', 'Kubota D1803'), ('D-243', 'ММЗ Д-243'), ('V3300', 'Kubota V3300'), ('K21', 'Nissan K21'), ('MMZ-4D', 'MMZ-4D')], default='D1803', max_length=16)),
                ('n_tranc', models.CharField(max_length=32)),
                ('type_tranc', models.CharField(choices=[('HF30', 'HF30-VP010'), ('HF50', 'HF50-VP020'), ('10VA', '10VA-00105'), ('10VB', '10VB-00106')], default='HF30', max_length=16)),
                ('n_vmost', models.CharField(max_length=32)),
                ('type_vmost', models.CharField(choices=[('20VA', '20VA-00101'), ('20VB', '20VB-00102'), ('HA50', 'HA50-VP010'), ('HA30', 'HA30-02020')], default='20VA', max_length=16)),
                ('n_cmost', models.CharField(max_length=32)),
                ('type_cmost', models.CharField(choices=[('B35', 'B350655A'), ('VS30', 'VS30-00001'), ('VS20', 'VS20-00001')], default='B35', max_length=16)),
                ('order', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('options', models.TextField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equip.buyer')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equip.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_machines', to='equip.company')),
            ],
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_to', models.CharField(choices=[('TO-0', 'ТО-0 (50 м/час)'), ('TO-1', 'ТО-1 (200 м/час)'), ('TO-2', 'ТО-2 (400 м/час)'), ('TO-4', 'ТО-4 (1000м/час)'), ('TO-5', 'ТО-5 (2000м/час)')], default='TO-0', max_length=12)),
                ('date', models.DateField()),
                ('narabotka', models.CharField(max_length=8)),
                ('order', models.CharField(max_length=16)),
                ('date_order', models.DateField()),
                ('doTOservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_do_tos', to='equip.company')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_tos', to='equip.machine')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tos', to='equip.company')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('narabotka', models.CharField(max_length=8)),
                ('detail', models.CharField(max_length=32)),
                ('info', models.TextField()),
                ('fix', models.TextField()),
                ('fix_detail', models.TextField()),
                ('fix_date', models.DateField()),
                ('stop_date', models.CharField(max_length=8)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_claims', to='equip.machine')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_claims', to='equip.company')),
            ],
        ),
    ]
