# Generated by Django 4.2.3 on 2023-08-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCmost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeTranc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeVmost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='buyer',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_client', to='equip.client'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_service', to='equip.company'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.AlterField(
            model_name='machine',
            name='type_cmost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_typecmost', to='equip.typecmost'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_typemachine', to='equip.typemachine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type_motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_typemotor', to='equip.typemotor'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type_tranc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_typetranc', to='equip.typetranc'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type_vmost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_typevmost', to='equip.typevmost'),
        ),
    ]
